name: update project list

on:
  schedule:
    - cron: "0 21,3,9 * * *" # JST 6:00, 12:00, 18:00 (UTC 21:00, 3:00, 9:00)
  workflow_dispatch:

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

concurrency:
  group: crawl-and-insert
  cancel-in-progress: false

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v4

      - name: pnpm セットアップ
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Node.js セットアップ
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: パッケージインストール
        run: pnpm install

      - name: Playwright インストール
        run: pnpm exec playwright install --with-deps

      - name: クローリング
        run: pnpm dlx tsx ./crawl.ts

      - name: データ更新
        run: pnpm dlx tsx ./insert-to-notion.ts
